gui-name: "&cShop"
gui-rows: 5
gui-sellitem:
  material: "EMERALD"
  displayname: "&cClick to Sell (&a%total%&c)"
gui-bottomrow:
  material: "GRAY_STAINED_GLASS_PANE"
  displayname: " "
receipt:
  message: "&eHover over me to view receipt!"
  header: "&bYou sold:"
  format: "%amount%x &c%material%&r = &a %price%"
gui-item-enumeration-format: "%amount%x &c%material%&r = &a %price%"
message-sold: "&aSold all items for &c%total%&a!"
command: "sell"
on-sell:
  run-command: "discord bcast #1234567890 %player% has just sold items %items% for a total sell cost of %cost%"
  cost-locale:
    lang: "en"
    country: "US"
  items-format: [ "%cost% of %name%", ", ", " and " ]
# sell prices. I suggest to use /ushop setprice in game for adding items, or use /ushop convert in order to use your essentialsx prices!